language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-eyeglass' ]; then cd .. && eval "mv $currentfolder generator-eyeglass" && cd generator-eyeglass; fi
